# Mestrado Informática
# Pós-Graduação Data Science and Digital Transformation
## (Ambientes de) Programação para Ciência de Dados
## Ficha Prática 2 - NumPy

**Miguel de Campos Rodrigues - 27089**

1. Use a biblioteca NumPy para criar um vetor de 24 valores aleatórios inteiros entre 10 e 20. Utilize esta biblioteca para responder às seguintes questões.

In [59]:
import numpy as np

print("Numpy Version:", np.version.full_version)

Numpy Version: 2.3.4


<ol type="a">
    <li>Crie uma cópia do vetor original e substitua os elementos do vetor com índice ímpar com o valor -5 (sem alterar o vetor original).</li>
    <li>Extraia do vetor original os valores entre 10 (inclusive) e 15 (inclusive)</li>
    <li>Extraia do vetor original os valores superiores a 15.</li>
    <li>Converta o vetor inicial numa matriz M de 2 dimensões com 6 linhas e 4 colunas.</li>
    <li>Extraia da matriz M a segunda e terceira coluna.</li>
    <li>Extraia da matriz M as duas últimas linhas.</li>
    <li>Empilhe a matriz resultou na alínea e. com a transposta da matriz que resultou da alínea f. Justifique o tipo de empilhamento usado (vertical ou horizontal)</li>
    <li>Use a matriz M e inverta a ordem dos elementos da primeira coluna e da última coluna</li>
    <li>Use a matriz M e inverta a ordem dos elementos da primeira linha e última linha.</li>
</ol>

In [60]:
vector = np.random.randint(10, 21, size=24)
print(vector)

[16 10 16 15 20 15 18 19 12 18 15 12 13 18 15 10 16 15 17 17 18 20 15 14]


In [61]:
# a.
vector_a = vector.copy()
vector_a[1::2] = -5
print(vector_a)

[16 -5 16 -5 20 -5 18 -5 12 -5 15 -5 13 -5 15 -5 16 -5 17 -5 18 -5 15 -5]


In [62]:
# b.
vector_b = vector[(vector >= 10) & (vector <= 15)]
print(vector_b)

[10 15 15 12 15 12 13 15 10 15 15 14]


In [63]:
# c.
vector_c = vector[vector > 15]
print(vector_c)

[16 16 20 18 19 18 18 16 17 17 18 20]


In [64]:
# d.
M = vector.reshape(6, 4)
print(M)

[[16 10 16 15]
 [20 15 18 19]
 [12 18 15 12]
 [13 18 15 10]
 [16 15 17 17]
 [18 20 15 14]]


In [65]:
# e.
matrix_e = M[:, 1:3]
print(matrix_e)

[[10 16]
 [15 18]
 [18 15]
 [18 15]
 [15 17]
 [20 15]]


In [66]:
# f.
matrix_f = M[-2:, :]
print(matrix_f)

[[16 15 17 17]
 [18 20 15 14]]


In [ ]:
# g.
# Usa-se empilhamento vertical porque a matrix_e é 2 colunas por 6 linhas e a transposta
# de matrix_f é 2 colunas por 4 linhas. Para que funcione é necessário empilhar pelo eixo
# com o mesmo tamanho, caso contrário falha com uma excepção.

stack = np.vstack((matrix_e, matrix_f.T))
print(stack)

[[10 16]
 [15 18]
 [18 15]
 [18 15]
 [15 17]
 [20 15]
 [16 18]
 [15 20]
 [17 15]
 [17 14]]


In [68]:
# h.
matrix_h = M.copy()
matrix_h[:, 0] = matrix_h[:, 0][::-1]
matrix_h[:, -1] = matrix_h[:, -1][::-1]
print(matrix_h)

[[18 10 16 14]
 [16 15 18 17]
 [13 18 15 10]
 [12 18 15 12]
 [20 15 17 19]
 [16 20 15 15]]


In [69]:
# i.
matrix_i = M.copy()
matrix_i[0 ,:] = matrix_i[0 ,:][::-1]
matrix_i[-1 ,:] = matrix_i[-1 ,:][::-1]
print(matrix_i)

[[15 16 10 16]
 [20 15 18 19]
 [12 18 15 12]
 [13 18 15 10]
 [16 15 17 17]
 [14 15 20 18]]



2. O dataset iris contém informação sobre as dimensões (comprimento e largura) das sépalas e pétalas de três espécies de flores iris.
O dataset pode ser lido da sua localização no repositório da UC Irvine para uma matriz numpy (iris) através das seguintes instruções:

In [70]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

Utilize a biblioteca numpy para resolver as seguintes questões:<ol type="a">
<li>Verifique qual é a forma da matriz iris criada com as instruções anteriores. Cada linha corresponde a uma flor. Quantas flores estão representadas no dataset?</li>
<li>Verifique que a última coluna da matriz contém elementos que não são numéricos (nan) e descarte essa coluna da matriz. Verifique a alteração da forma da matriz.</li>
<li>Verifique agora se a matriz <code>iris</code> contém algum elemento que não seja um número (nan)<br/>
    A primeira coluna de <code>iris</code> representa o comprimento das sépalas.<br/>
    A segunda coluna de <code>iris</code> representa a largura das sépalas<br/>
    A terceira coluna de <code>iris</code> representa o comprimento das pétalas<br/>
    A quarta coluna de <code>iris</code> representa a largura das pétalas
</li>

<li>Determine a média, mediana e desvio padrão das quantidades representadas em cada coluna.</li>
<li>Ordene a matriz por ordem crescente de comprimento das pétalas.</li>
<li>Crie uma segunda matriz que contém os elementos de iris em que o comprimento das sépalas é superior a <code>1.5</code> e o comprimento das pétalas é menor que <code>1.5</code>. Quantos exemplares existem com essas duas condições?</li>

In [71]:
# a.
print("Forma da matriz:", iris.shape)
print("Número de flores:", iris.shape[0])

Forma da matriz: (150, 5)
Número de flores: 150


In [72]:
# b.
def to_float_or_nan(x):
    try:
        return float(x)
    except:
        return np.nan

def check_NaNs(matrix):
    print("Existem NaNs!" if np.isnan(matrix).any() else "Não exitem NaNs.")

iris_float = np.vectorize(to_float_or_nan)(iris)
check_NaNs(iris_float)
iris_truncated = iris_float[:, :-1]
print("Forma da Matriz:", iris_truncated.shape)

Existem NaNs!
Forma da Matriz: (150, 4)


In [94]:
# c.
check_NaNs(iris_truncated)

def print_matrix(matrix):
    columns = ["Comprimento sépala", "Largura sépala", "Comprimento pétala", "Largura pétala"]
    print("+--------------------+----------------+--------------------+----------------+")
    print("| {:} | {:} | {:} | {:} |".format(*columns))
    print("+--------------------+----------------+--------------------+----------------+")
    for row in matrix:
        print("| {:18.2f} | {:14.2f} | {:18.2f} | {:14.2f} |".format(*row))
    print("|                ... |            ... |                ... |            ... |")
    print("+--------------------+----------------+--------------------+----------------+")

print_matrix(iris_truncated[:5])

Não exitem NaNs.
+--------------------+----------------+--------------------+----------------+
| Comprimento sépala | Largura sépala | Comprimento pétala | Largura pétala |
+--------------------+----------------+--------------------+----------------+
|               5.10 |           3.50 |               1.40 |           0.20 |
|               4.90 |           3.00 |               1.40 |           0.20 |
|               4.70 |           3.20 |               1.30 |           0.20 |
|               4.60 |           3.10 |               1.50 |           0.20 |
|               5.00 |           3.60 |               1.40 |           0.20 |
|                ... |            ... |                ... |            ... |
+--------------------+----------------+--------------------+----------------+


In [95]:
# d.
mean = np.mean(iris_truncated, axis=0)
median = np.median(iris_truncated, axis=0)
std = np.std(iris_truncated, axis=0)

print("Estatísticas por coluna:")
for i, name in enumerate(columns):
    print(f"{name}\n\tMean: {mean[i]:.2f}, Mediana: {median[i]:.2f}, Desvio Padrão: {std[i]:.2f}")

Estatísticas por coluna:
Comprimento sépala
	Mean: 5.84, Mediana: 5.80, Desvio Padrão: 0.83
Largura sépala
	Mean: 3.05, Mediana: 3.00, Desvio Padrão: 0.43
Comprimento pétala
	Mean: 3.76, Mediana: 4.35, Desvio Padrão: 1.76
Largura pétala
	Mean: 1.20, Mediana: 1.30, Desvio Padrão: 0.76


In [97]:
# e.
print("iris original:")
print_matrix(iris_truncated[:5])

iris_sorted = iris_truncated[iris[:, 2].argsort()]
print("\niris ordenada:")
print_matrix(iris_sorted[:5])

iris original:
+--------------------+----------------+--------------------+----------------+
| Comprimento sépala | Largura sépala | Comprimento pétala | Largura pétala |
+--------------------+----------------+--------------------+----------------+
|               5.10 |           3.50 |               1.40 |           0.20 |
|               4.90 |           3.00 |               1.40 |           0.20 |
|               4.70 |           3.20 |               1.30 |           0.20 |
|               4.60 |           3.10 |               1.50 |           0.20 |
|               5.00 |           3.60 |               1.40 |           0.20 |
|                ... |            ... |                ... |            ... |
+--------------------+----------------+--------------------+----------------+

iris ordenada:
+--------------------+----------------+--------------------+----------------+
| Comprimento sépala | Largura sépala | Comprimento pétala | Largura pétala |
+--------------------+-----------

In [ ]:
# f.
print("Número total de flores:", iris_truncated.shape[0])
iris_filtered = iris_truncated[(iris_truncated[:, 0] > 1.5) & (iris_truncated[:, 2] < 1.5)]
print("Número de flores filtradas (sépalas > 1.5 & pétalas < 1.5):", iris_filtered.shape[0])

Número total de flores: 150
Número de flores filtradas (sépalas > 1.5 & pétalas < 1.5): 23
